// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYZLFstbak99NJ8MJup1jlkh7_IDDRrAo',
    appId: '1:144437310976:web:be60e2803d30d5763fcae5',
    messagingSenderId: '144437310976',
    projectId: 'gizi-fit-app',
    authDomain: 'gizi-fit-app.firebaseapp.com',
    storageBucket: 'gizi-fit-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-ZbWPmgL0uvJFhTUQ3kET5BEbaFo55dY',
    appId: '1:144437310976:android:f5961529cde92a5f3fcae5',
    messagingSenderId: '144437310976',
    projectId: 'gizi-fit-app',
    storageBucket: 'gizi-fit-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6wMHHbove2gEK6lijzrRlbsf8k8luth0',
    appId: '1:144437310976:ios:7e4bc66cc0ddd4473fcae5',
    messagingSenderId: '144437310976',
    projectId: 'gizi-fit-app',
    storageBucket: 'gizi-fit-app.appspot.com',
    iosBundleId: 'com.example.giziFitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6wMHHbove2gEK6lijzrRlbsf8k8luth0',
    appId: '1:144437310976:ios:7e4bc66cc0ddd4473fcae5',
    messagingSenderId: '144437310976',
    projectId: 'gizi-fit-app',
    storageBucket: 'gizi-fit-app.appspot.com',
    iosBundleId: 'com.example.giziFitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYZLFstbak99NJ8MJup1jlkh7_IDDRrAo',
    appId: '1:144437310976:web:d0f1d5819b120a813fcae5',
    messagingSenderId: '144437310976',
    projectId: 'gizi-fit-app',
    authDomain: 'gizi-fit-app.firebaseapp.com',
    storageBucket: 'gizi-fit-app.appspot.com',
  );
}
